import React, { useState, useEffect, useRef } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { mathGenService as mathAPI } from "../../services/mathGenService";
import { evaluateService } from "../../services/evaluateService"; // Using service instead of utils/api
import { useTranslation } from "../../hooks/useTranslation";

// Interfaces
interface Step {
    header: string;
    description: string;
    calculation: string;
    answer: string;
}

interface Question {
    question: string;
    answer: string;
    solution: string;
    steps: Step[];
    rag_context_used?: boolean;
}

interface Quiz {
    success: boolean;
    topic: string;
    difficulty: "easy" | "medium" | "hard";
    questions: Question[];
    rag_context_used?: boolean;
}

interface Answer {
    stepAnswers: string[];
    finalAnswer: string;
    timeSpent: number;
}

interface EvaluationResult {
    isCorrect: boolean;
    marksObtained: number;
    feedback: string;
    explanation: string;
}

interface MathTopic {
    sinhala: string;
    english: string;
}

interface QuizTakingProps {
    user?: any;
}

const QuizTaking: React.FC<QuizTakingProps> = ({ user }) => {
    const { t, currentLanguage, changeLanguage } = useTranslation();
    const navigate = useNavigate();
    const location = useLocation();

    // Get params passed from QuizGenerator
    const passedParams = location.state || {};

    // Quiz state
    const [quiz, setQuiz] = useState<Quiz | null>(null);
    const [currentQuestion, setCurrentQuestion] = useState(0);
    const [answers, setAnswers] = useState<Answer[]>([]);
    const [markedQuestions, setMarkedQuestions] = useState<Set<number>>(new Set());
    const [loading, setLoading] = useState(false);
    const [generating, setGenerating] = useState(false);
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState("");
    const [showLanguageDropdown, setShowLanguageDropdown] = useState(false);
    const [showSolution, setShowSolution] = useState<{ [key: number]: boolean }>({});
    const [evaluationResults, setEvaluationResults] = useState<EvaluationResult[] | null>(null);
    const [isEvaluating, setIsEvaluating] = useState(false);

    // Generation options - initialized from passed params
    const [topic, setTopic] = useState(passedParams.topic || "වාරික ගණනය");
    const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">(passedParams.difficulty || "medium");
    const [numQuestions, setNumQuestions] = useState(passedParams.numQuestions || 5);
    const [topics, setTopics] = useState<MathTopic[]>([]);

    // Track if we should auto-generate
    const [shouldAutoGenerate, setShouldAutoGenerate] = useState(passedParams.autoGenerate || false);

    // Refs
    const questionStartTime = useRef<number | null>(null);
    const mathContainerRef = useRef<HTMLDivElement>(null);
    const inputRefs = useRef<{ [key: string]: HTMLInputElement | null }>({});
    const hasAutoGenerated = useRef(false);

    // Fetch available topics on mount
    useEffect(() => {
        fetchTopics();
    }, []);

    // Auto-generate if flag is set (from QuizGenerator navigation)
    useEffect(() => {
        if (shouldAutoGenerate && !hasAutoGenerated.current && topics.length > 0) {
            hasAutoGenerated.current = true;
            generateQuiz();
        }
    }, [shouldAutoGenerate, topics]);

    // Close language dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (showLanguageDropdown && !(event.target as Element).closest(".language-dropdown-container")) {
                setShowLanguageDropdown(false);
            }
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, [showLanguageDropdown]);

    // Track time when question changes
    useEffect(() => {
        if (quiz?.questions?.length && quiz.questions.length > 0) {
            questionStartTime.current = Date.now();
        }
    }, [currentQuestion, quiz]);

    const fetchTopics = async () => {
        try {
            const response: any = await mathAPI.getTopics();
            setTopics(response.topics || []);
        } catch (err) {
            console.error("Error fetching topics:", err);
            // Fallback topics
            setTopics([
                { sinhala: "වාරික ගණනය", english: "Installments" },
                { sinhala: "සරල පොලිය", english: "Simple Interest" },
                { sinhala: "ලාභ හානි", english: "Profit & Loss" },
            ]);
        }
    };

    const generateQuiz = async () => {
        setGenerating(true);
        setError("");

        try {
            const response: any = await mathAPI.generateQuestions({
                topic,
                difficulty,
                numQuestions,
            });

            if (response.success) {
                const parsedQuestions = response.questions.map((q: any) => ({
                    ...q,
                    steps: parseSteps(q.solution),
                }));

                setQuiz({
                    ...response,
                    questions: parsedQuestions,
                });

                const initialAnswers: Answer[] = parsedQuestions.map((q: any) => ({
                    stepAnswers: q.steps.map(() => ""),
                    finalAnswer: "",
                    timeSpent: 0,
                }));

                setAnswers(initialAnswers);
                setCurrentQuestion(0);
                setMarkedQuestions(new Set());
                setShowSolution({});
                questionStartTime.current = Date.now();
            } else {
                setError("Failed to generate questions");
            }
        } catch (err: any) {
            console.error("Error generating quiz:", err);
            setError(err.message || "Failed to generate questions. Please try again.");
        } finally {
            setGenerating(false);
            setShouldAutoGenerate(false);
        }
    };

    // Parse solution string into steps
    const parseSteps = (solution: string): Step[] => {
        if (!solution) return [];

        const lines = solution.split("\n").filter((line) => line.trim());
        const steps: Step[] = [];
        let currentStep: Step | null = null;

        for (const line of lines) {
            if (line.includes("පියවර") || line.match(/^step\s*\d+/i)) {
                if (currentStep) steps.push(currentStep);
                currentStep = {
                    header: line.trim(),
                    description: "",
                    calculation: "",
                    answer: "",
                };
            } else if (currentStep) {
                if (line.includes("=")) {
                    const parts = line.split("=");
                    if (parts.length >= 2) {
                        currentStep.description = parts[0].trim();
                        currentStep.answer = parts.slice(1).join("=").trim();
                        currentStep.calculation = line.trim();
                    }
                } else {
                    currentStep.description += (currentStep.description ? " " : "") + line.trim();
                }
            }
        }

        if (currentStep) steps.push(currentStep);
        return steps;
    };

    // Handle input change for a step
    const handleStepInputChange = (stepIndex: number, value: string) => {
        const newAnswers = [...answers];
        if (newAnswers[currentQuestion]) {
            newAnswers[currentQuestion].stepAnswers[stepIndex] = value;
            setAnswers(newAnswers);
        }
    };

    // Handle final answer change
    const handleFinalAnswerChange = (value: string) => {
        const newAnswers = [...answers];
        if (newAnswers[currentQuestion]) {
            newAnswers[currentQuestion].finalAnswer = value;
            setAnswers(newAnswers);
        }
    };

    // Insert mathematical notation
    const insertNotation = (stepIndex: number, notation: string) => {
        const inputKey = `step-${currentQuestion}-${stepIndex}`;
        const input = inputRefs.current[inputKey];

        if (input) {
            const start = input.selectionStart || 0;
            const end = input.selectionEnd || 0;
            const currentValue = answers[currentQuestion]?.stepAnswers[stepIndex] || "";
            const newValue = currentValue.substring(0, start) + notation + currentValue.substring(end);

            handleStepInputChange(stepIndex, newValue);

            setTimeout(() => {
                input.focus();
                input.setSelectionRange(start + notation.length, start + notation.length);
            }, 0);
        }
    };

    const insertFinalNotation = (notation: string) => {
        const input = inputRefs.current["final-answer"];

        if (input) {
            const start = input.selectionStart || 0;
            const end = input.selectionEnd || 0;
            const currentValue = answers[currentQuestion]?.finalAnswer || "";
            const newValue = currentValue.substring(0, start) + notation + currentValue.substring(end);

            handleFinalAnswerChange(newValue);

            setTimeout(() => {
                input.focus();
                input.setSelectionRange(start + notation.length, start + notation.length);
            }, 0);
        }
    };

    const saveTimeForCurrentQuestion = () => {
        if (questionStartTime.current && answers[currentQuestion]) {
            const time = Math.floor((Date.now() - questionStartTime.current) / 1000);
            const newAnswers = [...answers];
            newAnswers[currentQuestion].timeSpent += time;
            setAnswers(newAnswers);
        }
    };

    const handleNext = () => {
        if (quiz && currentQuestion < quiz.questions.length - 1) {
            saveTimeForCurrentQuestion();
            setCurrentQuestion(currentQuestion + 1);
            questionStartTime.current = Date.now();
        }
    };

    const handlePrevious = () => {
        if (currentQuestion > 0) {
            saveTimeForCurrentQuestion();
            setCurrentQuestion(currentQuestion - 1);
            questionStartTime.current = Date.now();
        }
    };

    const handleMarkForReview = () => {
        const newMarked = new Set(markedQuestions);
        if (newMarked.has(currentQuestion)) {
            newMarked.delete(currentQuestion);
        } else {
            newMarked.add(currentQuestion);
        }
        setMarkedQuestions(newMarked);
        handleNext();
    };

    const handleClearAnswer = () => {
        if (quiz && answers[currentQuestion]) {
            const newAnswers = [...answers];
            newAnswers[currentQuestion] = {
                stepAnswers: quiz.questions[currentQuestion].steps.map(() => ""),
                finalAnswer: "",
                timeSpent: answers[currentQuestion].timeSpent,
            };
            setAnswers(newAnswers);
        }
    };

    const handleQuestionClick = (index: number) => {
        saveTimeForCurrentQuestion();
        setCurrentQuestion(index);
        questionStartTime.current = Date.now();
    };

    const toggleShowSolution = (questionIndex: number) => {
        setShowSolution((prev) => ({
            ...prev,
            [questionIndex]: !prev[questionIndex],
        }));
    };

    const handleFinish = async () => {
        if (!window.confirm(t("quiz.areYouSure") || "Are you sure you want to finish? ")) {
            return;
        }

        setSubmitting(true);
        saveTimeForCurrentQuestion();

        if (!quiz) return;

        const questionsPayload = answers.map((answer, idx) => {
            const question = quiz.questions[idx];
            return {
                question: question.question,
                userStepAnswers: answer.stepAnswers,
                userFinalAnswer: answer.finalAnswer,
                correctAnswer: question.answer,
                solution: question.solution,
                timeSpent: answer.timeSpent,
            };
        });

        try {
            setIsEvaluating(true);
            const response: any = await evaluateService.evaluateBatch({ questions: questionsPayload });

            if (response.data && response.data.success) {
                setEvaluationResults(response.data.results);
            } else {
                setError("Evaluation failed. Please try again or check console.");
            }
        } catch (err) {
            console.error("Error evaluating quiz:", err);
            setError("Failed to submit quiz for evaluation.");
        } finally {
            setIsEvaluating(false);
            setSubmitting(false);
        }
    };

    const handleNewQuiz = () => {
        setQuiz(null);
        hasAutoGenerated.current = false;
        setEvaluationResults(null);
    };

    const handleBackToGenerator = () => {
        navigate('/quiz/generate');
    };

    const getQuestionStatus = (index: number) => {
        if (index === currentQuestion) return "current";
        if (markedQuestions.has(index)) return "marked";

        const answer = answers[index];
        if (answer) {
            const hasStepAnswers = answer.stepAnswers.some((a) => a.trim() !== "");
            const hasFinalAnswer = answer.finalAnswer.trim() !== "";
            if (hasStepAnswers || hasFinalAnswer) return "answered";
        }
        return "unanswered";
    };

    const mathNotations = [
        { symbol: "+", label: "+" },
        { symbol: "-", label: "-" },
        { symbol: "×", label: "×" },
        { symbol: "÷", label: "÷" },
        { symbol: "%", label: "%" },
        { symbol: "=", label: "=" },
        { symbol: "(", label: "(" },
        { symbol: ")", label: ")" },
        { symbol: "රු.", label: "රු." },
        { symbol: ",", label: "," },
    ];

    // Loading state while auto-generating
    if (generating && shouldAutoGenerate) {
        return (
            <div className="min-h-screen bg-gray-50 flex items-center justify-center">
                <div className="text-center">
                    <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary-600 mx-auto mb-4"></div>
                    <h2 className="text-xl font-semibold text-gray-800 mb-2">
                        ප්‍රශ්න ජනනය වෙමින් පවතී...
                    </h2>
                    <p className="text-gray-600">Generating {numQuestions} questions about {topic}</p>
                    <p className="text-sm text-gray-500 mt-2">Difficulty: {difficulty}</p>
                </div>
            </div>
        );
    }

    // Generation form if no quiz
    if (!quiz) {
        return (
            <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
                <header className="bg-primary-600 text-white shadow-md">
                    <div className="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="flex justify-between items-center h-14">
                            <div className="flex items-center space-x-4">
                                <button
                                    onClick={handleBackToGenerator}
                                    className="hover:text-primary-200 flex items-center"
                                >
                                    ← Back
                                </button>
                                <span className="font-semibold">සිංහල ගණිත ප්‍රශ්න</span>
                            </div>
                        </div>
                    </div>
                </header>

                <div className="max-w-2xl mx-auto px-4 py-8">
                    <div className="bg-white dark:bg-dominant-800 rounded-lg shadow-md p-6">
                        <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-2 text-center">
                            සිංහල ගණිත ප්‍රශ්න ජනකය
                        </h1>
                        <h2 className="text-lg text-gray-600 dark:text-gray-400 mb-6 text-center">
                            Sinhala Math Question Generator
                        </h2>

                        {error && (
                            <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
                                {error}
                                <button
                                    onClick={() => setError("")}
                                    className="float-right text-red-700 hover:text-red-900"
                                >
                                    ×
                                </button>
                            </div>
                        )}

                        <div className="space-y-4">
                            {/* Topic Selection */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                    විෂය මාතෘකාව (Topic)
                                </label>
                                <select
                                    value={topic}
                                    onChange={(e) => setTopic(e.target.value)}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                                    disabled={generating}
                                >
                                    {topics.map((t, idx) => (
                                        <option key={idx} value={t.sinhala}>
                                            {t.sinhala} ({t.english})
                                        </option>
                                    ))}
                                </select>
                            </div>

                            {/* Difficulty Selection */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                    අපහසුතා මට්ටම (Difficulty)
                                </label>
                                <select
                                    value={difficulty}
                                    onChange={(e) => setDifficulty(e.target.value as any)}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                                    disabled={generating}
                                >
                                    <option value="easy">පහසු (Easy)</option>
                                    <option value="medium">මධ්‍යම (Medium)</option>
                                    <option value="hard">අපහසු (Hard)</option>
                                </select>
                            </div>

                            {/* Number of Questions */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                    ප්‍රශ්න ගණන (Number of Questions)
                                </label>
                                <select
                                    value={numQuestions}
                                    onChange={(e) => setNumQuestions(parseInt(e.target.value))}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                                    disabled={generating}
                                >
                                    <option value={3}>3</option>
                                    <option value={5}>5</option>
                                    <option value={7}>7</option>
                                    <option value={10}>10</option>
                                </select>
                            </div>

                            {/* Generate Button */}
                            <button
                                onClick={generateQuiz}
                                disabled={generating}
                                className="w-full py-3 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-400 text-white font-semibold rounded-md transition-colors"
                            >
                                {generating ? (
                                    <span className="flex items-center justify-center">
                                        <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                        Generating...
                                    </span>
                                ) : (
                                    "ප්‍රශ්න ජනනය කරන්න (Generate Questions)"
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    // Results View
    if (evaluationResults) {
        const totalQuestions = quiz.questions.length;
        const correctCount = evaluationResults.filter(r => r.isCorrect).length;
        const percentage = Math.round((correctCount / totalQuestions) * 100);

        // Calculate total marks (assuming 10 marks per question for now or use marksObtained)
        const totalMarks = evaluationResults.reduce((acc, curr) => acc + (curr.marksObtained || 0), 0);
        const maxMarks = totalQuestions * 10; // Assuming 10 marks per question base

        let grade = { label: 'Participated', color: 'gray' };
        if (percentage >= 75) grade = { label: 'Excellent', color: 'green' };
        else if (percentage >= 50) grade = { label: 'Good', color: 'blue' };
        else if (percentage >= 35) grade = { label: 'Average', color: 'yellow' };
        else grade = { label: 'Needs Improvement', color: 'red' };

        return (
            <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
                <header className="bg-success-600 text-white shadow-md">
                    <div className="max-w-full mx-auto px-4 py-4">
                        <div className="flex justify-between items-center">
                            <span className="font-semibold">📋 {quiz.topic} - Results</span>
                            <button
                                onClick={handleNewQuiz}
                                className="bg-white text-success-700 px-4 py-2 rounded-md font-bold text-sm hover:bg-gray-100"
                            >
                                Start New Quiz
                            </button>
                        </div>
                    </div>
                </header>

                <div className="max-w-4xl mx-auto px-4 py-8">
                    {/* Score Card */}
                    <div className="bg-white dark:bg-dominant-800 rounded-xl shadow-lg p-6 mb-6">
                        <h2 className="text-2xl font-bold text-center text-gray-800 dark:text-gray-200 mb-6">🎯 Your Results</h2>

                        <div className="grid grid-cols-3 gap-4 mb-6">
                            <div className="bg-blue-50 dark:bg-blue-900/30 rounded-lg p-4 text-center">
                                <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">{correctCount}/{totalQuestions}</div>
                                <div className="text-sm text-gray-600 dark:text-gray-400">Correct Questions</div>
                            </div>
                            <div className="bg-green-50 dark:bg-green-900/30 rounded-lg p-4 text-center">
                                {/* Use parsed marks if available, else simple count */}
                                <div className="text-3xl font-bold text-green-600 dark:text-green-400">{totalMarks}</div>
                                <div className="text-sm text-gray-600 dark:text-gray-400">Total Marks</div>
                            </div>
                            <div className={`rounded-lg p-4 text-center bg-${grade.color}-100 dark:bg-${grade.color}-900/30`}>
                                <div className={`text-3xl font-bold text-${grade.color}-600 dark:text-${grade.color}-400`}>{percentage}%</div>
                                <div className="text-sm text-gray-600 dark:text-gray-400">{grade.label}</div>
                            </div>
                        </div>

                        <div className="flex justify-center gap-4">
                            <button onClick={() => navigate('/quiz/generate')} className="px-6 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-lg font-medium">
                                Try Another Topic
                            </button>
                        </div>
                    </div>

                    {/* Detailed Feedback */}
                    <div className="space-y-6">
                        {quiz.questions.map((q, idx) => {
                            const result = evaluationResults[idx] || {};
                            const isCorrect = result.isCorrect;
                            const userAnswer = answers[idx];

                            return (
                                <div key={idx} className={`bg-white dark:bg-dominant-800 rounded-xl shadow-md overflow-hidden border-2 ${isCorrect ? 'border-green-200 dark:border-green-800' : 'border-red-200 dark:border-red-800'}`}>
                                    <div className={`p-4 ${isCorrect ? 'bg-green-50 dark:bg-green-900/20' : 'bg-red-50 dark:bg-red-900/20'} flex justify-between items-center`}>
                                        <h3 className="font-bold text-gray-800 dark:text-gray-200">Question {idx + 1}</h3>
                                        <span className={`px-3 py-1 rounded-full text-sm font-bold ${isCorrect ? 'bg-green-200 text-green-800 dark:bg-green-800 dark:text-green-200' : 'bg-red-200 text-red-800 dark:bg-red-800 dark:text-red-200'}`}>
                                            {isCorrect ? 'Correct' : 'Incorrect'}
                                        </span>
                                    </div>

                                    <div className="p-6">
                                        <div className="mb-4 text-lg text-gray-800 dark:text-gray-200">{q.question}</div>

                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                                            <div className="p-3 bg-gray-50 dark:bg-dominant-700 rounded border dark:border-dominant-600">
                                                <div className="text-xs text-gray-500 dark:text-gray-400 uppercase font-bold mb-1">Your Answer</div>
                                                <div className="font-medium text-gray-800 dark:text-gray-200">
                                                    {userAnswer.finalAnswer || "No final answer"}
                                                    {userAnswer.stepAnswers.some(s => s) && (
                                                        <div className="mt-2 text-sm text-gray-600 dark:text-gray-400 border-t dark:border-dominant-600 pt-2">
                                                            Steps: {userAnswer.stepAnswers.map((s, i) => s ? <div key={i}>{i + 1}. {s}</div> : null)}
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded border border-blue-100 dark:border-blue-800">
                                                <div className="text-xs text-blue-500 dark:text-blue-400 uppercase font-bold mb-1">Correct Answer</div>
                                                <div className="font-medium text-gray-800 dark:text-gray-200">{q.answer}</div>
                                            </div>
                                        </div>

                                        {/* AI Feedback */}
                                        <div className="bg-indigo-50 dark:bg-indigo-900/20 p-4 rounded-lg border border-indigo-100 dark:border-indigo-800">
                                            <h4 className="flex items-center text-indigo-800 dark:text-indigo-400 font-bold mb-2">
                                                <span className="mr-2">🤖</span> AI Feedback
                                            </h4>
                                            <p className="text-gray-700 dark:text-gray-300 whitespace-pre-line">{result.feedback || result.explanation || "No specific feedback available."}</p>
                                            {result.explanation && result.feedback !== result.explanation && (
                                                <p className="mt-2 text-sm text-gray-600 dark:text-gray-400 border-t border-indigo-200 dark:border-indigo-700 pt-2">{result.explanation}</p>
                                            )}
                                        </div>

                                        {/* Solution Toggle */}
                                        <div className="mt-4">
                                            <button
                                                onClick={() => toggleShowSolution(idx)}
                                                className="text-sm text-primary-600 dark:text-primary-400 hover:text-primary-800 dark:hover:text-primary-300 underline"
                                            >
                                                {showSolution[idx] ? "Hide Full Solution" : "Show Full Solution"}
                                            </button>
                                            {showSolution[idx] && (
                                                <div className="mt-2 p-3 bg-gray-100 dark:bg-dominant-700 rounded text-sm font-mono whitespace-pre-wrap dark:text-gray-200">
                                                    {q.solution}
                                                </div>
                                            )}
                                        </div>

                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        );
    }

    // Quiz taking UI
    const question = quiz.questions[currentQuestion];
    const currentAnswer = answers[currentQuestion];
    const answeredCount = answers.filter(
        (a) => a && (a.stepAnswers.some((s) => s.trim()) || a.finalAnswer.trim())
    ).length;
    const markedCount = markedQuestions.size;

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
            {/* Header */}
            <header className="bg-primary-600 text-white shadow-md">
                <div className="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between items-center h-14">
                        <div className="flex items-center space-x-4 sm:space-x-6 overflow-x-auto">
                            <button
                                onClick={handleBackToGenerator}
                                className="hover:text-primary-200 whitespace-nowrap"
                            >
                                ← Back
                            </button>
                            <span className="font-semibold whitespace-nowrap">
                                {quiz.topic} - {quiz.difficulty}
                            </span>
                        </div>
                        <div className="flex items-center space-x-3 ml-4">
                            <div className="relative language-dropdown-container">
                                <button
                                    onClick={() => setShowLanguageDropdown(!showLanguageDropdown)}
                                    className="px-3 py-1 bg-primary-500 hover:bg-primary-400 rounded text-sm flex items-center"
                                >
                                    {currentLanguage === "en" ? "English" : "සිංහල"} ▾
                                </button>
                                {showLanguageDropdown && (
                                    <div className="absolute right-0 mt-1 bg-white dark:bg-dominant-800 border border-gray-300 dark:border-dominant-600 rounded shadow-lg z-10">
                                        <button
                                            onClick={() => { changeLanguage("en"); setShowLanguageDropdown(false); }}
                                            className="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-dominant-700 text-gray-700 dark:text-gray-200"
                                        >
                                            English
                                        </button>
                                        <button
                                            onClick={() => { changeLanguage("si"); setShowLanguageDropdown(false); }}
                                            className="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-dominant-700 text-gray-700 dark:text-gray-200"
                                        >
                                            සිංහල
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <div className="flex flex-col lg:flex-row max-w-full">
                {/* Left Content Area */}
                <div className="flex-1 bg-white dark:bg-dominant-800 p-4 sm:p-6 lg:p-8">
                    {/* Question Header */}
                    <div className="flex justify-between items-center mb-4">
                        <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-200">
                            ප්‍රශ්නය {currentQuestion + 1} / {quiz.questions.length}
                        </h2>
                        {quiz.rag_context_used && (
                            <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded">
                                RAG Enhanced
                            </span>
                        )}
                    </div>

                    {/* Question Text */}
                    <div className="mb-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border-l-4 border-primary-500">
                        <div ref={mathContainerRef} className="text-lg text-gray-800 dark:text-gray-200 leading-relaxed">
                            {question.question}
                        </div>
                    </div>

                    {/* Step-by-Step Input Fields */}
                    <div className="space-y-4 mb-6">
                        <h3 className="text-md font-semibold text-gray-700 dark:text-gray-300">
                            විසඳුම ලියන්න (Write your solution):
                        </h3>

                        {question.steps.map((step, stepIndex) => (
                            <div key={stepIndex} className="bg-gray-50 dark:bg-dominant-700 rounded-lg p-4 border border-gray-200 dark:border-dominant-600">
                                <div className="text-sm font-medium text-primary-600 dark:text-primary-400 mb-2">
                                    {step.header}
                                </div>

                                <div className="flex flex-col sm:flex-row sm:items-center gap-2">
                                    {step.description && (
                                        <div className="text-gray-700 dark:text-gray-300 font-medium min-w-fit">
                                            {step.description} =
                                        </div>
                                    )}

                                    <div className="flex-1">
                                        <input
                                            ref={(el) => { inputRefs.current[`step-${currentQuestion}-${stepIndex}`] = el; }}
                                            type="text"
                                            value={currentAnswer?.stepAnswers[stepIndex] || ""}
                                            onChange={(e) => handleStepInputChange(stepIndex, e.target.value)}
                                            placeholder="පිළිතුර ලියන්න..."
                                            className="w-full px-3 py-2 border border-gray-300 dark:border-dominant-500 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white dark:bg-dominant-800 text-lg dark:text-white"
                                            dir="auto"
                                        />
                                    </div>

                                    <div className="flex flex-wrap gap-1">
                                        {mathNotations.map((notation) => (
                                            <button
                                                key={notation.symbol}
                                                type="button"
                                                onClick={() => insertNotation(stepIndex, notation.symbol)}
                                                className="px-2 py-1 bg-gray-200 dark:bg-dominant-600 hover:bg-gray-300 dark:hover:bg-dominant-500 text-gray-700 dark:text-gray-200 rounded text-sm font-medium min-w-[32px]"
                                            >
                                                {notation.label}
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                {showSolution[currentQuestion] && (
                                    <div className="mt-2 text-sm text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-3 py-1 rounded">
                                        නිවැරදි පිළිතුර: {step.answer}
                                    </div>
                                )}
                            </div>
                        ))}

                        {/* Final Answer */}
                        <div className="bg-yellow-50 dark:bg-yellow-900/10 rounded-lg p-4 border-2 border-yellow-400 dark:border-yellow-600">
                            <div className="text-md font-semibold text-gray-700 dark:text-gray-300 mb-2">
                                අවසාන පිළිතුර (Final Answer):
                            </div>
                            <div className="flex flex-col sm:flex-row sm:items-center gap-2">
                                <div className="flex-1">
                                    <input
                                        ref={(el) => { inputRefs.current["final-answer"] = el; }}
                                        type="text"
                                        value={currentAnswer?.finalAnswer || ""}
                                        onChange={(e) => handleFinalAnswerChange(e.target.value)}
                                        placeholder="අවසාන පිළිතුර ලියන්න..."
                                        className="w-full px-3 py-2 border-2 border-yellow-400 dark:border-yellow-600 rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-500 dark:focus:ring-yellow-600 bg-white dark:bg-dominant-800 text-lg font-medium dark:text-white"
                                        dir="auto"
                                    />
                                </div>
                                <div className="flex flex-wrap gap-1">
                                    {mathNotations.map((notation) => (
                                        <button
                                            key={`final-${notation.symbol}`}
                                            type="button"
                                            onClick={() => insertFinalNotation(notation.symbol)}
                                            className="px-2 py-1 bg-yellow-200 dark:bg-yellow-800/40 hover:bg-yellow-300 dark:hover:bg-yellow-800/60 text-gray-700 dark:text-gray-200 rounded text-sm font-medium min-w-[32px]"
                                        >
                                            {notation.label}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            {showSolution[currentQuestion] && (
                                <div className="mt-2 text-sm text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-3 py-2 rounded">
                                    නිවැරදි පිළිතුර: {question.answer}
                                </div>
                            )}
                        </div>
                    </div>

                    <div className="flex justify-between items-center mt-6">
                        <button
                            onClick={handlePrevious}
                            disabled={submitting || currentQuestion === 0}
                            className={`px-4 py-2 bg-gray-200 dark:bg-dominant-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-dominant-600 disabled:opacity-50 transition-colors`}
                        >
                            Previous
                        </button>
                        <div className="flex gap-2">
                            <button
                                onClick={handleMarkForReview}
                                className={`px-4 py-2 border border-yellow-500 text-yellow-600 dark:text-yellow-400 rounded-lg hover:bg-yellow-50 dark:hover:bg-yellow-900/20 transition-colors ${markedQuestions.has(currentQuestion) ? 'bg-yellow-100 dark:bg-yellow-900/40' : ''}`}
                            >
                                {markedQuestions.has(currentQuestion) ? 'Unmark' : 'Mark for Review'}
                            </button>
                            <button
                                onClick={handleClearAnswer}
                                className="px-4 py-2 border border-red-500 text-red-600 dark:text-red-400 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
                            >
                                Clear
                            </button>
                        </div>
                        {currentQuestion === quiz.questions.length - 1 ? (
                            <button
                                onClick={handleFinish}
                                disabled={submitting}
                                className="px-6 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg shadow-md transition-colors disabled:opacity-50"
                            >
                                {submitting ? 'Submitting...' : 'Finish & Submit'}
                            </button>
                        ) : (
                            <button
                                onClick={handleNext}
                                disabled={submitting}
                                className="px-6 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg shadow-md transition-colors"
                            >
                                Next
                            </button>
                        )}
                    </div>
                </div>

                {/* Right Sidebar - Navigation (Collapsible on mobile?) */}
                <div className="w-full lg:w-72 bg-gray-100 dark:bg-dominant-900 border-l border-gray-200 dark:border-dominant-700 p-4">
                    {/* Timer or Status */}
                    <div className="mb-6 bg-white dark:bg-dominant-800 p-4 rounded-lg shadow-sm">
                        <div className="text-center">
                            <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">Time Elapsed</p>
                            <p className="text-2xl font-mono font-bold text-gray-800 dark:text-gray-200">
                                {/* Timer not implemented in original logic but structure is here, can add later */}
                                --:--
                            </p>
                        </div>
                    </div>

                    <div className="mb-6">
                        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Questions</h3>
                        <div className="grid grid-cols-5 gap-2">
                            {quiz.questions.map((_, index) => {
                                const status = getQuestionStatus(index);
                                let bgColor = "bg-gray-200 dark:bg-dominant-700 text-gray-700 dark:text-gray-300"; // Unanswered
                                if (status === "current") bgColor = "ring-2 ring-primary-500 bg-white dark:bg-dominant-800 text-primary-700 dark:text-primary-300 font-bold";
                                else if (status === "marked") bgColor = "bg-yellow-200 dark:bg-yellow-800 text-yellow-800 dark:text-yellow-200";
                                else if (status === "answered") bgColor = "bg-green-200 dark:bg-green-800 text-green-800 dark:text-green-200";

                                return (
                                    <button
                                        key={index}
                                        onClick={() => handleQuestionClick(index)}
                                        className={`w-10 h-10 rounded-lg text-sm font-medium hover:opacity-80 transition-all ${bgColor}`}
                                    >
                                        {index + 1}
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* Legend */}
                    <div className="mb-6">
                        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">සලකුණු</h3>
                        <div className="space-y-2 text-sm">
                            <div className="flex items-center">
                                <div className="w-4 h-4 rounded mr-2 border-2 border-primary-500 bg-white dark:bg-dominant-800"></div>
                                <span className="text-gray-600 dark:text-gray-400">වත්මන්</span>
                            </div>
                            <div className="flex items-center">
                                <div className="w-4 h-4 bg-green-200 dark:bg-green-800 rounded mr-2"></div>
                                <span className="text-gray-600 dark:text-gray-400">පිළිතුරු දුන්</span>
                            </div>
                            <div className="flex items-center">
                                <div className="w-4 h-4 bg-yellow-200 dark:bg-yellow-800 rounded mr-2"></div>
                                <span className="text-gray-600 dark:text-gray-400">සලකුණු කළ</span>
                            </div>
                            <div className="flex items-center">
                                <div className="w-4 h-4 bg-gray-200 dark:bg-dominant-700 rounded mr-2"></div>
                                <span className="text-gray-600 dark:text-gray-400">ඉතිරි</span>
                            </div>
                        </div>
                    </div>

                    {/* Summary */}
                    <div>
                        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">සාරාංශය</h3>
                        <div className="space-y-1 text-sm">
                            <div className="flex justify-between">
                                <span className="text-green-600 dark:text-green-400">පිළිතුරු:</span>
                                <span className="font-medium text-gray-800 dark:text-gray-200">{answeredCount}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-yellow-600 dark:text-yellow-400">සලකුණු:</span>
                                <span className="font-medium text-gray-800 dark:text-gray-200">{markedCount}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600 dark:text-gray-400">ඉතිරි:</span>
                                <span className="font-medium text-gray-800 dark:text-gray-200">{quiz.questions.length - answeredCount}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Error Toast */}
            {error && (
                <div className="fixed bottom-4 right-4 bg-red-100 dark:bg-red-900 border border-red-400 dark:border-red-700 text-red-700 dark:text-red-300 px-4 py-3 rounded shadow-lg max-w-md">
                    <div className="flex justify-between items-start">
                        <span>{error}</span>
                        <button onClick={() => setError("")} className="ml-2 text-red-700 dark:text-red-300 hover:text-red-900 dark:hover:text-red-100">✕</button>
                    </div>
                </div>
            )}
        </div>
    );
};

export default QuizTaking;
