import React, { useState, useEffect, useRef, useMemo } from "react";
import { useNavigate, useLocation, useParams } from "react-router-dom";
import { mathGenService as mathAPI } from "../../services/mathGenService";
import { evaluateService } from "../../services/evaluateService";
import { useTranslation } from "../../hooks/useTranslation";
import { useMathQuiz } from "../../hooks/useMathQuiz";
import {
  type ParsedStep,
  type MathNotation,
  parseSolutionSteps,
  getNotationsForTopic,
} from "../../api/questionApi";

// ==================== Interfaces ====================

interface Question {
  question: string;
  answer: string;
  solution: string;
  /** Parsed structured steps (derived from solution) */
  parsedSteps: ParsedStep[];
  rag_context_used?: boolean;
}

interface Quiz {
  success: boolean;
  topic: string;
  difficulty: "easy" | "medium" | "hard";
  questions: Question[];
  rag_context_used?: boolean;
}

/**
 * One answer per question.
 * `stepAnswers` is keyed by the index of *input* steps only
 * (readonly steps don't have user answers).
 */
interface Answer {
  /** Map from inputStepIndex → user's typed value */
  stepAnswers: string[];
  finalAnswer: string;
  timeSpent: number;
}

interface EvaluationResult {
  isCorrect: boolean;
  marksObtained: number;
  feedback: string;
  explanation: string;
}

interface MathTopic {
  sinhala: string;
  english: string;
}

interface QuizTakingProps {
  user?: any;
}

// ==================== Component ====================

const QuizTaking: React.FC<QuizTakingProps> = ({ user }) => {
  const { t, currentLanguage, changeLanguage } = useTranslation();
  const navigate = useNavigate();
  const location = useLocation();
  const { quizId } = useParams();
  const { saveQuiz, getQuizById, submitQuiz: submitQuizToDB } = useMathQuiz();

  const passedParams = location.state || {};

  // ----- Quiz state -----
  const [quiz, setQuiz] = useState<Quiz | null>(null);
  const [savedQuizId, setSavedQuizId] = useState<string | null>(null);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [markedQuestions, setMarkedQuestions] = useState<Set<number>>(
    new Set(),
  );
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [totalTimeElapsed, setTotalTimeElapsed] = useState(0);
  const [error, setError] = useState("");
  const [showLanguageDropdown, setShowLanguageDropdown] = useState(false);

  // NEW: global "view answers" toggle so student can peek during exam
  const [showAnswers, setShowAnswers] = useState(false);

  const [evaluationResults, setEvaluationResults] = useState<
    EvaluationResult[] | null
  >(null);
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [showSolution, setShowSolution] = useState<Record<number, boolean>>({});

  // ----- Generation options -----
  const [topic, setTopic] = useState(passedParams.topic || "පොළිය");
  const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">(
    passedParams.difficulty || "medium",
  );
  const [numQuestions, setNumQuestions] = useState(
    passedParams.numQuestions || 5,
  );
  const [topics, setTopics] = useState<MathTopic[]>([]);
  const [shouldAutoGenerate, setShouldAutoGenerate] = useState(
    passedParams.autoGenerate || false,
  );

  // Refs
  const questionStartTime = useRef<number | null>(null);
  const inputRefs = useRef<Record<string, HTMLInputElement | null>>({});
  const hasAutoGenerated = useRef(false);

  // ==================== Derived: topic-specific notations ====================
  const currentTopic = quiz?.topic || topic;
  const notations: MathNotation[] = useMemo(
    () => getNotationsForTopic(currentTopic),
    [currentTopic],
  );

  // ==================== Effects ====================

  useEffect(() => {
    fetchTopics();
  }, []);

  useEffect(() => {
    if (quizId) loadQuizById(quizId);
  }, [quizId]);

  useEffect(() => {
    if (shouldAutoGenerate && !hasAutoGenerated.current && topics.length > 0) {
      hasAutoGenerated.current = true;
      generateQuiz();
    }
  }, [shouldAutoGenerate, topics]);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (
        showLanguageDropdown &&
        !(e.target as Element).closest(".language-dropdown-container")
      ) {
        setShowLanguageDropdown(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [showLanguageDropdown]);

  useEffect(() => {
    if (quiz?.questions?.length) questionStartTime.current = Date.now();
  }, [currentQuestion, quiz]);

  useEffect(() => {
    if (!quiz || evaluationResults || generating) return;
    const timer = setInterval(() => setTotalTimeElapsed((p) => p + 1), 1000);
    return () => clearInterval(timer);
  }, [quiz, evaluationResults, generating]);

  // ==================== Helpers ====================

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  };

  /**
   * Count how many input-type steps a question has.
   * This determines the length of stepAnswers[].
   */
  const countInputSteps = (parsedSteps: ParsedStep[]): number =>
    parsedSteps.filter((s) => s.type === "input").length;

  /**
   * Build initial empty Answer for a question
   */
  const buildEmptyAnswer = (q: Question): Answer => ({
    stepAnswers: Array(countInputSteps(q.parsedSteps)).fill(""),
    finalAnswer: "",
    timeSpent: 0,
  });

  // ==================== Data loading ====================

  const fetchTopics = async () => {
    try {
      const response: any = await mathAPI.getTopics();
      setTopics(response.topics || []);
    } catch {
      setTopics([
        { sinhala: "පොළිය", english: "Interest" },
        { sinhala: "සමීකරණ", english: "Equations" },
        { sinhala: "කොටස් වෙළෙඳපොළ", english: "Stock Market" },
        { sinhala: "ලඝුගණක", english: "Logarithms" },
        { sinhala: "ශ්‍රීඝ්‍රතාවය", english: "Speed" },
        { sinhala: "සමාන්තර ශ්‍රේණි", english: "Arithmetic Progression" },
      ]);
    }
  };

  const loadQuizById = async (id: string) => {
    try {
      setLoading(true);
      const quizData: any = await getQuizById(id);
      if (!quizData) return;

      const parsedQuestions: Question[] = quizData.questions.map((q: any) => ({
        ...q,
        parsedSteps: parseSolutionSteps(q.solution || ""),
      }));

      const quizObj: Quiz = {
        success: true,
        topic: quizData.topic,
        difficulty: quizData.difficulty,
        questions: parsedQuestions,
        rag_context_used: quizData.rag_context_used,
      };
      setQuiz(quizObj);
      setSavedQuizId(quizData.id);
      setTopic(quizData.topic);
      setDifficulty(quizData.difficulty);

      // Restore answers
      if (quizData.userAnswers?.length) {
        setAnswers(
          quizData.userAnswers.map((ua: any, idx: number) => ({
            stepAnswers:
              ua.stepAnswers ||
              Array(countInputSteps(parsedQuestions[idx].parsedSteps)).fill(""),
            finalAnswer: ua.finalAnswer || "",
            timeSpent: ua.timeSpent || 0,
          })),
        );
      } else {
        setAnswers(parsedQuestions.map(buildEmptyAnswer));
      }

      if (quizData.status === "completed") {
        setEvaluationResults(
          quizData.userAnswers.map((ua: any) => ({
            isCorrect: ua.isCorrect || false,
            marksObtained: ua.marksObtained || 0,
            feedback: ua.feedback || "",
            explanation: ua.explanation || "",
          })),
        );
      }
    } catch (err) {
      console.error("Failed to load quiz:", err);
      setError("Failed to load quiz.");
    } finally {
      setLoading(false);
    }
  };

  // ==================== Generation ====================

  const generateQuiz = async () => {
    setGenerating(true);
    setError("");
    setShowAnswers(false);

    try {
      const response: any = await mathAPI.generateQuestions({
        topic,
        difficulty,
        numQuestions,
      });

      if (!response.success) {
        setError("Failed to generate questions");
        return;
      }

      const parsedQuestions: Question[] = response.questions.map((q: any) => ({
        ...q,
        parsedSteps: parseSolutionSteps(q.solution || ""),
      }));

      const quizData: Quiz = { ...response, questions: parsedQuestions };
      setQuiz(quizData);
      setAnswers(parsedQuestions.map(buildEmptyAnswer));
      setCurrentQuestion(0);
      setMarkedQuestions(new Set());
      setShowSolution({});
      setTotalTimeElapsed(0);
      setEvaluationResults(null);
      questionStartTime.current = Date.now();

      // Persist to DB
      try {
        const topicEnglish =
          topics.find((t) => t.sinhala === topic)?.english || topic;
        const saved = await saveQuiz({
          topic,
          topicEnglish,
          difficulty,
          questions: parsedQuestions,
          rag_context_used: response.rag_context_used || false,
        });
        if (saved?.id) setSavedQuizId(saved.id);
      } catch (e) {
        console.error("Failed to save quiz to DB:", e);
      }
    } catch (err: any) {
      setError(
        err.message || "Failed to generate questions. Please try again.",
      );
    } finally {
      setGenerating(false);
      setShouldAutoGenerate(false);
    }
  };

  // ==================== Answer handling ====================

  /**
   * inputIndex refers to the nth *input* step (skipping readonly).
   */
  const handleStepInputChange = (inputIndex: number, value: string) => {
    setAnswers((prev) => {
      const copy = [...prev];
      if (copy[currentQuestion]) {
        const sa = [...copy[currentQuestion].stepAnswers];
        sa[inputIndex] = value;
        copy[currentQuestion] = { ...copy[currentQuestion], stepAnswers: sa };
      }
      return copy;
    });
  };

  const handleFinalAnswerChange = (value: string) => {
    setAnswers((prev) => {
      const copy = [...prev];
      if (copy[currentQuestion]) {
        copy[currentQuestion] = {
          ...copy[currentQuestion],
          finalAnswer: value,
        };
      }
      return copy;
    });
  };

  const insertNotation = (inputIndex: number, notation: string) => {
    const key = `step-${currentQuestion}-${inputIndex}`;
    const input = inputRefs.current[key];
    if (!input) return;

    const start = input.selectionStart || 0;
    const end = input.selectionEnd || 0;
    const cur = answers[currentQuestion]?.stepAnswers[inputIndex] || "";
    const next = cur.substring(0, start) + notation + cur.substring(end);
    handleStepInputChange(inputIndex, next);
    setTimeout(() => {
      input.focus();
      input.setSelectionRange(start + notation.length, start + notation.length);
    }, 0);
  };

  const insertFinalNotation = (notation: string) => {
    const input = inputRefs.current["final-answer"];
    if (!input) return;

    const start = input.selectionStart || 0;
    const end = input.selectionEnd || 0;
    const cur = answers[currentQuestion]?.finalAnswer || "";
    const next = cur.substring(0, start) + notation + cur.substring(end);
    handleFinalAnswerChange(next);
    setTimeout(() => {
      input.focus();
      input.setSelectionRange(start + notation.length, start + notation.length);
    }, 0);
  };

  // ==================== Navigation ====================

  const saveTimeForCurrentQuestion = () => {
    if (!questionStartTime.current || !answers[currentQuestion]) return;
    const time = Math.floor((Date.now() - questionStartTime.current) / 1000);
    setAnswers((prev) => {
      const copy = [...prev];
      copy[currentQuestion] = {
        ...copy[currentQuestion],
        timeSpent: copy[currentQuestion].timeSpent + time,
      };
      return copy;
    });
  };

  const handleNext = () => {
    if (quiz && currentQuestion < quiz.questions.length - 1) {
      saveTimeForCurrentQuestion();
      setCurrentQuestion(currentQuestion + 1);
      questionStartTime.current = Date.now();
    }
  };

  const handlePrevious = () => {
    if (currentQuestion > 0) {
      saveTimeForCurrentQuestion();
      setCurrentQuestion(currentQuestion - 1);
      questionStartTime.current = Date.now();
    }
  };

  const handleMarkForReview = () => {
    setMarkedQuestions((prev) => {
      const copy = new Set(prev);
      copy.has(currentQuestion)
        ? copy.delete(currentQuestion)
        : copy.add(currentQuestion);
      return copy;
    });
    handleNext();
  };

  const handleClearAnswer = () => {
    if (!quiz) return;
    const q = quiz.questions[currentQuestion];
    setAnswers((prev) => {
      const copy = [...prev];
      copy[currentQuestion] = {
        stepAnswers: Array(countInputSteps(q.parsedSteps)).fill(""),
        finalAnswer: "",
        timeSpent: prev[currentQuestion].timeSpent,
      };
      return copy;
    });
  };

  const handleQuestionClick = (index: number) => {
    saveTimeForCurrentQuestion();
    setCurrentQuestion(index);
    questionStartTime.current = Date.now();
  };

  const toggleShowSolution = (idx: number) => {
    setShowSolution((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  // ==================== Submission ====================

  const handleFinish = async () => {
    if (
      !window.confirm(
        t("quiz.areYouSure") || "Are you sure you want to finish?",
      )
    )
      return;
    if (!quiz) return;

    setSubmitting(true);
    saveTimeForCurrentQuestion();

    const questionsPayload = answers.map((answer, idx) => {
      const q = quiz.questions[idx];
      return {
        question: q.question,
        userStepAnswers: answer.stepAnswers,
        userFinalAnswer: answer.finalAnswer,
        correctAnswer: q.answer,
        solution: q.solution,
        timeSpent: answer.timeSpent,
      };
    });

    try {
      setIsEvaluating(true);
      const response: any =
        await evaluateService.evaluateBatch(questionsPayload);

      if (response.data?.success) {
        const results = response.data.results;
        setEvaluationResults(results);

        if (savedQuizId) {
          try {
            await submitQuizToDB(savedQuizId, answers, results);
          } catch (e) {
            console.error("Failed to save results to DB:", e);
          }
        }
      } else {
        setError("Evaluation failed. Please try again.");
      }
    } catch (err) {
      console.error("Error evaluating quiz:", err);
      setError("Failed to submit quiz for evaluation.");
    } finally {
      setIsEvaluating(false);
      setSubmitting(false);
    }
  };

  const handleNewQuiz = () => {
    setQuiz(null);
    hasAutoGenerated.current = false;
    setEvaluationResults(null);
    setShowAnswers(false);
  };

  const handleBackToGenerator = () => navigate("/quiz/generate");

  const getQuestionStatus = (index: number) => {
    if (index === currentQuestion) return "current";
    if (markedQuestions.has(index)) return "marked";
    const a = answers[index];
    if (a && (a.stepAnswers.some((s) => s.trim()) || a.finalAnswer.trim()))
      return "answered";
    return "unanswered";
  };

  // ==================== Render: Loading ====================

  if (generating && shouldAutoGenerate) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-dominant-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mb-2">
            ප්‍රශ්න ජනනය වෙමින් පවතී...
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Generating {numQuestions} questions about {topic}
          </p>
          <p className="text-sm text-gray-500 dark:text-gray-500 mt-2">
            Difficulty: {difficulty}
          </p>
        </div>
      </div>
    );
  }

  // ==================== Render: No quiz yet (generation form) ====================

  if (!quiz) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
        <header className="bg-primary-600 text-white shadow-md">
          <div className="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-14">
              <div className="flex items-center space-x-4">
                <button
                  onClick={handleBackToGenerator}
                  className="hover:text-primary-200 flex items-center"
                >
                  ← Back
                </button>
                <span className="font-semibold">සිංහල ගණිත ප්‍රශ්න</span>
              </div>
            </div>
          </div>
        </header>

        <div className="max-w-2xl mx-auto px-4 py-8">
          <div className="bg-white dark:bg-dominant-800 rounded-lg shadow-md p-6">
            <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-2 text-center">
              සිංහල ගණිත ප්‍රශ්න ජනකය
            </h1>
            <h2 className="text-lg text-gray-600 dark:text-gray-400 mb-6 text-center">
              Sinhala Math Question Generator
            </h2>

            {error && (
              <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
                {error}
                <button
                  onClick={() => setError("")}
                  className="float-right text-red-700 hover:text-red-900"
                >
                  ×
                </button>
              </div>
            )}

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  විෂය මාතෘකාව (Topic)
                </label>
                <select
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                  disabled={generating}
                >
                  {topics.map((t, idx) => (
                    <option key={idx} value={t.sinhala}>
                      {t.sinhala} ({t.english})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  අපහසුතා මට්ටම (Difficulty)
                </label>
                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value as any)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                  disabled={generating}
                >
                  <option value="easy">පහසු (Easy)</option>
                  <option value="medium">මධ්‍යම (Medium)</option>
                  <option value="hard">අපහසු (Hard)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  ප්‍රශ්න ගණන (Number of Questions)
                </label>
                <select
                  value={numQuestions}
                  onChange={(e) => setNumQuestions(parseInt(e.target.value))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500 dark:bg-dominant-700 dark:border-dominant-600 dark:text-white"
                  disabled={generating}
                >
                  <option value={3}>3</option>
                  <option value={5}>5</option>
                  <option value={7}>7</option>
                  <option value={10}>10</option>
                </select>
              </div>

              <button
                onClick={generateQuiz}
                disabled={generating}
                className="w-full py-3 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-400 text-white font-semibold rounded-md transition-colors"
              >
                {generating ? (
                  <span className="flex items-center justify-center">
                    <svg
                      className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    Generating...
                  </span>
                ) : (
                  "ප්‍රශ්න ජනනය කරන්න (Generate Questions)"
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ==================== Render: Results View ====================

  if (evaluationResults) {
    const totalQuestions = quiz.questions.length;
    const correctCount = evaluationResults.filter((r) => r.isCorrect).length;
    const percentage = Math.round((correctCount / totalQuestions) * 100);
    const totalMarks = evaluationResults.reduce(
      (acc, curr) => acc + (curr.marksObtained || 0),
      0,
    );

    let grade = { label: "Needs Improvement", color: "red" };
    if (percentage >= 75) grade = { label: "Excellent", color: "green" };
    else if (percentage >= 50) grade = { label: "Good", color: "blue" };
    else if (percentage >= 35) grade = { label: "Average", color: "yellow" };

    return (
      <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
        <header className="bg-success-600 text-white shadow-md">
          <div className="max-w-full mx-auto px-4 py-4">
            <div className="flex justify-between items-center">
              <span className="font-semibold">📋 {quiz.topic} - Results</span>
              <button
                onClick={handleNewQuiz}
                className="bg-white text-success-700 px-4 py-2 rounded-md font-bold text-sm hover:bg-gray-100"
              >
                Start New Quiz
              </button>
            </div>
          </div>
        </header>

        <div className="max-w-4xl mx-auto px-4 py-8">
          {/* Score Card */}
          <div className="bg-white dark:bg-dominant-800 rounded-xl shadow-lg p-6 mb-6">
            <h2 className="text-2xl font-bold text-center text-gray-800 dark:text-gray-200 mb-6">
              🎯 Your Results
            </h2>

            <div className="grid grid-cols-3 gap-4 mb-6">
              <div className="bg-blue-50 dark:bg-blue-900/30 rounded-lg p-4 text-center">
                <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">
                  {correctCount}/{totalQuestions}
                </div>
                <div className="text-sm text-gray-600 dark:text-gray-400">
                  Correct
                </div>
              </div>
              <div className="bg-green-50 dark:bg-green-900/30 rounded-lg p-4 text-center">
                <div className="text-3xl font-bold text-green-600 dark:text-green-400">
                  {totalMarks}
                </div>
                <div className="text-sm text-gray-600 dark:text-gray-400">
                  Total Marks
                </div>
              </div>
              <div
                className={`bg-${grade.color}-50 dark:bg-${grade.color}-900/30 rounded-lg p-4 text-center`}
              >
                <div
                  className={`text-3xl font-bold text-${grade.color}-600 dark:text-${grade.color}-400`}
                >
                  {percentage}%
                </div>
                <div className="text-sm text-gray-600 dark:text-gray-400">
                  {grade.label}
                </div>
              </div>
            </div>

            <div className="flex justify-center gap-4">
              <button
                onClick={() => navigate("/quiz/generate")}
                className="px-6 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-lg font-medium"
              >
                Try Another Topic
              </button>
            </div>
          </div>

          {/* Detailed Feedback per question */}
          <div className="space-y-6">
            {quiz.questions.map((q, idx) => {
              const result = evaluationResults[idx] || ({} as EvaluationResult);
              const isCorrect = result.isCorrect;
              const userAnswer = answers[idx];

              // Rebuild input-step mapping for display
              let inputIdx = 0;

              return (
                <div
                  key={idx}
                  className={`bg-white dark:bg-dominant-800 rounded-xl shadow-md overflow-hidden border-2 ${
                    isCorrect
                      ? "border-green-200 dark:border-green-800"
                      : "border-red-200 dark:border-red-800"
                  }`}
                >
                  {/* Header */}
                  <div
                    className={`p-4 ${
                      isCorrect
                        ? "bg-green-50 dark:bg-green-900/20"
                        : "bg-red-50 dark:bg-red-900/20"
                    } flex justify-between items-center`}
                  >
                    <h3 className="font-bold text-gray-800 dark:text-gray-200">
                      Question {idx + 1}
                    </h3>
                    <span
                      className={`px-3 py-1 rounded-full text-sm font-bold ${
                        isCorrect
                          ? "bg-green-200 text-green-800 dark:bg-green-800 dark:text-green-200"
                          : "bg-red-200 text-red-800 dark:bg-red-800 dark:text-red-200"
                      }`}
                    >
                      {isCorrect ? "✓ Correct" : "✗ Incorrect"}
                    </span>
                  </div>

                  <div className="p-6">
                    {/* Question text */}
                    <div className="mb-4 text-lg text-gray-800 dark:text-gray-200 leading-relaxed">
                      {q.question}
                    </div>

                    {/* Step-by-step comparison */}
                    <div className="mb-4 space-y-2">
                      <h4 className="text-sm font-bold text-gray-600 dark:text-gray-400 uppercase tracking-wide mb-2">
                        Step-by-step Review
                      </h4>
                      {q.parsedSteps.map((step, sIdx) => {
                        if (step.type === "readonly") {
                          return (
                            <div
                              key={sIdx}
                              className="text-sm font-semibold text-primary-700 dark:text-primary-400 mt-3"
                            >
                              {step.description}
                            </div>
                          );
                        }

                        // Input step — compare
                        const thisInputIdx = inputIdx++;
                        const userVal =
                          userAnswer?.stepAnswers[thisInputIdx] || "";
                        const expected = step.expectedAnswer;
                        const stepCorrect =
                          userVal.trim().replace(/\s/g, "") ===
                          expected.trim().replace(/\s/g, "");

                        return (
                          <div
                            key={sIdx}
                            className={`flex flex-col sm:flex-row sm:items-center gap-2 p-3 rounded-lg border ${
                              stepCorrect
                                ? "bg-green-50 border-green-200 dark:bg-green-900/10 dark:border-green-800"
                                : "bg-red-50 border-red-200 dark:bg-red-900/10 dark:border-red-800"
                            }`}
                          >
                            <div className="text-sm text-gray-700 dark:text-gray-300 min-w-[200px]">
                              {step.description} =
                            </div>
                            <div className="flex-1 flex flex-col gap-1">
                              <div className="text-sm">
                                <span className="text-gray-500 dark:text-gray-400">
                                  Your:{" "}
                                </span>
                                <span
                                  className={
                                    stepCorrect
                                      ? "text-green-700 dark:text-green-400 font-medium"
                                      : "text-red-700 dark:text-red-400 font-medium line-through"
                                  }
                                >
                                  {userVal || "(empty)"}
                                </span>
                              </div>
                              {!stepCorrect && (
                                <div className="text-sm">
                                  <span className="text-gray-500 dark:text-gray-400">
                                    Expected:{" "}
                                  </span>
                                  <span className="text-green-700 dark:text-green-400 font-medium">
                                    {expected}
                                  </span>
                                </div>
                              )}
                            </div>
                            <div className="flex-shrink-0">
                              {stepCorrect ? (
                                <span className="text-green-600 text-lg">
                                  ✓
                                </span>
                              ) : (
                                <span className="text-red-600 text-lg">✗</span>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {/* Final answer comparison */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                      <div className="p-3 bg-gray-50 dark:bg-dominant-700 rounded border dark:border-dominant-600">
                        <div className="text-xs text-gray-500 dark:text-gray-400 uppercase font-bold mb-1">
                          Your Final Answer
                        </div>
                        <div className="font-medium text-gray-800 dark:text-gray-200">
                          {userAnswer?.finalAnswer || "(No final answer)"}
                        </div>
                      </div>
                      <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded border border-blue-100 dark:border-blue-800">
                        <div className="text-xs text-blue-500 dark:text-blue-400 uppercase font-bold mb-1">
                          Correct Answer
                        </div>
                        <div className="font-medium text-gray-800 dark:text-gray-200">
                          {q.answer}
                        </div>
                      </div>
                    </div>

                    {/* AI Feedback */}
                    <div className="bg-indigo-50 dark:bg-indigo-900/20 p-4 rounded-lg border border-indigo-100 dark:border-indigo-800">
                      <h4 className="flex items-center text-indigo-800 dark:text-indigo-400 font-bold mb-2">
                        <span className="mr-2">🤖</span> AI Feedback
                      </h4>
                      <p className="text-gray-700 dark:text-gray-300 whitespace-pre-line">
                        {result.feedback ||
                          result.explanation ||
                          "No specific feedback available."}
                      </p>
                      {result.explanation &&
                        result.feedback !== result.explanation && (
                          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400 border-t border-indigo-200 dark:border-indigo-700 pt-2">
                            {result.explanation}
                          </p>
                        )}
                    </div>

                    {/* Full solution toggle */}
                    <div className="mt-4">
                      <button
                        onClick={() => toggleShowSolution(idx)}
                        className="text-sm text-primary-600 dark:text-primary-400 hover:text-primary-800 dark:hover:text-primary-300 underline"
                      >
                        {showSolution[idx]
                          ? "Hide Full Solution"
                          : "Show Full Solution"}
                      </button>
                      {showSolution[idx] && (
                        <div className="mt-2 p-3 bg-gray-100 dark:bg-dominant-700 rounded text-sm font-mono whitespace-pre-wrap dark:text-gray-200">
                          {q.solution}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  }

  // ==================== Render: Quiz Taking UI ====================

  const question = quiz.questions[currentQuestion];
  const currentAnswer = answers[currentQuestion];
  const answeredCount = answers.filter(
    (a) => a && (a.stepAnswers.some((s) => s.trim()) || a.finalAnswer.trim()),
  ).length;
  const markedCount = markedQuestions.size;

  // Build a mapping: for each parsedStep, if it's "input" type, what is its inputIndex?
  // This lets us connect the right stepAnswers[] slot to each input field.
  let renderInputIdx = 0;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-dominant-900">
      {/* ===== Header ===== */}
      <header className="bg-primary-600 text-white shadow-md sticky top-0 z-50">
        <div className="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-14">
            <div className="flex items-center space-x-4 sm:space-x-6 overflow-x-auto">
              <button
                onClick={handleBackToGenerator}
                className="hover:text-primary-200 whitespace-nowrap"
              >
                ← Back
              </button>
              <span className="font-semibold whitespace-nowrap">
                {quiz.topic} - {quiz.difficulty}
              </span>
              <div className="hidden sm:flex items-center bg-primary-700 px-3 py-1 rounded-full text-sm font-mono">
                <svg
                  className="h-4 w-4 mr-2"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                {formatTime(totalTimeElapsed)}
              </div>
            </div>

            <div className="flex items-center space-x-3 ml-4">
              {/* View Answers Toggle */}
              <button
                onClick={() => setShowAnswers((prev) => !prev)}
                className={`px-3 py-1 rounded text-sm font-medium transition-colors ${
                  showAnswers
                    ? "bg-yellow-400 text-yellow-900"
                    : "bg-primary-500 hover:bg-primary-400 text-white"
                }`}
                title="Toggle showing correct answers for each step"
              >
                {showAnswers ? "🔓 Hide Answers" : "👁 View Answers"}
              </button>

              {/* Language Dropdown */}
              <div className="relative language-dropdown-container">
                <button
                  onClick={() => setShowLanguageDropdown(!showLanguageDropdown)}
                  className="px-3 py-1 bg-primary-500 hover:bg-primary-400 rounded text-sm flex items-center"
                >
                  {currentLanguage === "en" ? "English" : "සිංහල"} ▾
                </button>
                {showLanguageDropdown && (
                  <div className="absolute right-0 mt-1 bg-white dark:bg-dominant-800 border border-gray-300 dark:border-dominant-600 rounded shadow-lg z-10">
                    <button
                      onClick={() => {
                        changeLanguage("en");
                        setShowLanguageDropdown(false);
                      }}
                      className="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-dominant-700 text-gray-700 dark:text-gray-200"
                    >
                      English
                    </button>
                    <button
                      onClick={() => {
                        changeLanguage("si");
                        setShowLanguageDropdown(false);
                      }}
                      className="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 dark:hover:bg-dominant-700 text-gray-700 dark:text-gray-200"
                    >
                      සිංහල
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* ===== Main Content ===== */}
      <div className="flex flex-col lg:flex-row max-w-full">
        {/* Left: Question & Steps */}
        <div className="flex-1 bg-white dark:bg-dominant-800 p-4 sm:p-6 lg:p-8">
          {/* Question header */}
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-200">
              ප්‍රශ්නය {currentQuestion + 1} / {quiz.questions.length}
            </h2>
            <div className="flex items-center gap-2">
              {quiz.rag_context_used && (
                <span className="text-xs bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 px-2 py-1 rounded">
                  RAG Enhanced
                </span>
              )}
              {/* Mobile timer */}
              <span className="sm:hidden text-sm font-mono text-gray-600 dark:text-gray-400">
                {formatTime(totalTimeElapsed)}
              </span>
            </div>
          </div>

          {/* Question Text */}
          <div className="mb-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border-l-4 border-primary-500">
            <div className="text-lg text-gray-800 dark:text-gray-200 leading-relaxed">
              {question.question}
            </div>
          </div>

          {/* ===== Step-by-Step Section ===== */}
          <div className="space-y-3 mb-6">
            <h3 className="text-md font-semibold text-gray-700 dark:text-gray-300">
              විසඳුම ලියන්න (Write your solution):
            </h3>

            {(() => {
              // Reset input counter for this render pass
              let inputCounter = 0;

              return question.parsedSteps.map((step, sIdx) => {
                // ---- READONLY step (step header or plain description) ----
                if (step.type === "readonly") {
                  const isStepHeader = /^පියවර\s*\d+/.test(step.description);
                  return (
                    <div
                      key={sIdx}
                      className={
                        isStepHeader
                          ? "text-sm font-bold text-primary-700 dark:text-primary-400 mt-4 pb-1 border-b border-primary-200 dark:border-primary-800"
                          : "text-sm text-gray-700 dark:text-gray-300 pl-3"
                      }
                    >
                      {step.description}
                    </div>
                  );
                }

                // ---- INPUT step ----
                const thisInputIdx = inputCounter;
                inputCounter++;

                return (
                  <div
                    key={sIdx}
                    className="bg-gray-50 dark:bg-dominant-700 rounded-lg p-4 border border-gray-200 dark:border-dominant-600 ml-3"
                  >
                    {/* Description (left of =) */}
                    <div className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      {step.description} =
                    </div>

                    {/* Input field */}
                    <input
                      ref={(el) => {
                        inputRefs.current[
                          `step-${currentQuestion}-${thisInputIdx}`
                        ] = el;
                      }}
                      type="text"
                      value={currentAnswer?.stepAnswers[thisInputIdx] || ""}
                      onChange={(e) =>
                        handleStepInputChange(thisInputIdx, e.target.value)
                      }
                      placeholder="පිළිතුර මෙහි ලියන්න..."
                      className="w-full px-4 py-3 border border-gray-300 dark:border-dominant-500 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white dark:bg-dominant-800 text-lg dark:text-white shadow-sm"
                      dir="auto"
                    />

                    {/* Topic-specific notation buttons */}
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {notations.map((n) => (
                        <button
                          key={n.symbol}
                          type="button"
                          onClick={() => insertNotation(thisInputIdx, n.symbol)}
                          className="px-2.5 py-1.5 bg-gray-200 dark:bg-dominant-600 hover:bg-gray-300 dark:hover:bg-dominant-500 text-gray-800 dark:text-gray-200 rounded text-sm font-medium min-w-[36px] shadow-sm transition-colors"
                        >
                          {n.label}
                        </button>
                      ))}
                    </div>

                    {/* Show correct answer when "View Answers" is toggled ON */}
                    {showAnswers && (
                      <div className="mt-2 text-sm text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-3 py-2 rounded flex items-center gap-2">
                        <span className="font-medium">නිවැරදි:</span>
                        <span className="font-mono">{step.expectedAnswer}</span>
                      </div>
                    )}
                  </div>
                );
              });
            })()}

            {/* ===== Final Answer ===== */}
            <div className="bg-yellow-50 dark:bg-yellow-900/10 rounded-lg p-4 border-2 border-yellow-400 dark:border-yellow-600 mt-4">
              <div className="text-md font-semibold text-gray-700 dark:text-gray-300 mb-2">
                අවසාන පිළිතුර (Final Answer):
              </div>
              <div className="flex flex-col sm:flex-row sm:items-center gap-2">
                <div className="flex-1">
                  <input
                    ref={(el) => {
                      inputRefs.current["final-answer"] = el;
                    }}
                    type="text"
                    value={currentAnswer?.finalAnswer || ""}
                    onChange={(e) => handleFinalAnswerChange(e.target.value)}
                    placeholder="අවසාන පිළිතුර ලියන්න..."
                    className="w-full px-3 py-2 border-2 border-yellow-400 dark:border-yellow-600 rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-500 bg-white dark:bg-dominant-800 text-lg font-medium dark:text-white"
                    dir="auto"
                  />
                </div>
                <div className="flex flex-wrap gap-1">
                  {notations.map((n) => (
                    <button
                      key={`final-${n.symbol}`}
                      type="button"
                      onClick={() => insertFinalNotation(n.symbol)}
                      className="px-2 py-1 bg-yellow-200 dark:bg-yellow-800/40 hover:bg-yellow-300 dark:hover:bg-yellow-800/60 text-gray-700 dark:text-gray-200 rounded text-sm font-medium min-w-[32px]"
                    >
                      {n.label}
                    </button>
                  ))}
                </div>
              </div>

              {showAnswers && (
                <div className="mt-2 text-sm text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-3 py-2 rounded flex items-center gap-2">
                  <span className="font-medium">නිවැරදි:</span>
                  <span className="font-mono">{question.answer}</span>
                </div>
              )}
            </div>
          </div>

          {/* ===== Navigation Buttons ===== */}
          <div className="flex justify-between items-center mt-6">
            <button
              onClick={handlePrevious}
              disabled={submitting || currentQuestion === 0}
              className="px-4 py-2 bg-gray-200 dark:bg-dominant-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-dominant-600 disabled:opacity-50 transition-colors"
            >
              ← Previous
            </button>
            <div className="flex gap-2">
              <button
                onClick={handleMarkForReview}
                className={`px-4 py-2 border border-yellow-500 text-yellow-600 dark:text-yellow-400 rounded-lg hover:bg-yellow-50 dark:hover:bg-yellow-900/20 transition-colors ${
                  markedQuestions.has(currentQuestion)
                    ? "bg-yellow-100 dark:bg-yellow-900/40"
                    : ""
                }`}
              >
                {markedQuestions.has(currentQuestion) ? "Unmark" : "⚑ Mark"}
              </button>
              <button
                onClick={handleClearAnswer}
                className="px-4 py-2 border border-red-500 text-red-600 dark:text-red-400 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
              >
                Clear
              </button>
            </div>
            {currentQuestion === quiz.questions.length - 1 ? (
              <button
                onClick={handleFinish}
                disabled={submitting}
                className="px-6 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg shadow-md transition-colors disabled:opacity-50"
              >
                {submitting ? "Submitting..." : "✓ Finish & Submit"}
              </button>
            ) : (
              <button
                onClick={handleNext}
                disabled={submitting}
                className="px-6 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg shadow-md transition-colors"
              >
                Next →
              </button>
            )}
          </div>
        </div>

        {/* ===== Right Sidebar ===== */}
        <div className="w-full lg:w-72 bg-gray-100 dark:bg-dominant-900 border-l border-gray-200 dark:border-dominant-700 p-4">
          {/* Timer */}
          <div className="mb-6 bg-white dark:bg-dominant-800 p-4 rounded-lg shadow-sm">
            <div className="text-center">
              <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">
                Time Elapsed
              </p>
              <p className="text-2xl font-mono font-bold text-gray-800 dark:text-gray-200">
                {formatTime(totalTimeElapsed)}
              </p>
            </div>
          </div>

          {/* Topic info badge */}
          <div className="mb-4 bg-white dark:bg-dominant-800 p-3 rounded-lg shadow-sm">
            <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-bold mb-1">
              Topic
            </p>
            <p className="text-sm font-medium text-gray-800 dark:text-gray-200">
              {quiz.topic}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 capitalize">
              {quiz.difficulty}
            </p>
          </div>

          {/* Question grid */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
              Questions
            </h3>
            <div className="grid grid-cols-5 gap-2">
              {quiz.questions.map((_, index) => {
                const status = getQuestionStatus(index);
                let bgColor =
                  "bg-gray-200 dark:bg-dominant-700 text-gray-700 dark:text-gray-300";
                if (status === "current")
                  bgColor =
                    "ring-2 ring-primary-500 bg-white dark:bg-dominant-800 text-primary-700 dark:text-primary-300 font-bold";
                else if (status === "marked")
                  bgColor =
                    "bg-yellow-200 dark:bg-yellow-800 text-yellow-800 dark:text-yellow-200";
                else if (status === "answered")
                  bgColor =
                    "bg-green-200 dark:bg-green-800 text-green-800 dark:text-green-200";

                return (
                  <button
                    key={index}
                    onClick={() => handleQuestionClick(index)}
                    className={`w-10 h-10 rounded-lg text-sm font-medium hover:opacity-80 transition-all ${bgColor}`}
                  >
                    {index + 1}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Legend */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
              සලකුණු
            </h3>
            <div className="space-y-2 text-sm">
              {[
                {
                  color:
                    "border-2 border-primary-500 bg-white dark:bg-dominant-800",
                  label: "වත්මන්",
                },
                {
                  color: "bg-green-200 dark:bg-green-800",
                  label: "පිළිතුරු දුන්",
                },
                {
                  color: "bg-yellow-200 dark:bg-yellow-800",
                  label: "සලකුණු කළ",
                },
                { color: "bg-gray-200 dark:bg-dominant-700", label: "ඉතිරි" },
              ].map(({ color, label }) => (
                <div key={label} className="flex items-center">
                  <div className={`w-4 h-4 rounded mr-2 ${color}`} />
                  <span className="text-gray-600 dark:text-gray-400">
                    {label}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Summary */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
              සාරාංශය
            </h3>
            <div className="space-y-1 text-sm">
              <div className="flex justify-between">
                <span className="text-green-600 dark:text-green-400">
                  පිළිතුරු:
                </span>
                <span className="font-medium text-gray-800 dark:text-gray-200">
                  {answeredCount}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-yellow-600 dark:text-yellow-400">
                  සලකුණු:
                </span>
                <span className="font-medium text-gray-800 dark:text-gray-200">
                  {markedCount}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600 dark:text-gray-400">ඉතිරි:</span>
                <span className="font-medium text-gray-800 dark:text-gray-200">
                  {quiz.questions.length - answeredCount}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Error toast */}
      {error && (
        <div className="fixed bottom-4 right-4 bg-red-100 dark:bg-red-900 border border-red-400 dark:border-red-700 text-red-700 dark:text-red-300 px-4 py-3 rounded shadow-lg max-w-md z-50">
          <div className="flex justify-between items-start">
            <span>{error}</span>
            <button
              onClick={() => setError("")}
              className="ml-2 text-red-700 dark:text-red-300 hover:text-red-900 dark:hover:text-red-100"
            >
              ✕
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default QuizTaking;
