const mongoose = require('mongoose');

/**
 * Normalized Recommendation Model
 * Stores all recommendations generated by the system
 */
const recommendationSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  recommendationType: {
    type: String,
    enum: ['adaptive', 'knowledge-state', 'topic-priority', 'review', 'challenge'],
    required: true
  },
  recommendedTopic: String,
  recommendedTopicId: String,
  recommendedAction: {
    type: String,
    required: true
  },
  optimalQuestionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Question'
  },
  predictedSuccessRate: {
    type: Number,
    min: 0,
    max: 1
  },
  masteryLevel: {
    type: Number,
    min: 0,
    max: 1
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  },
  goal: {
    type: mongoose.Schema.Types.Mixed,
    default: null
  },
  knowledgeState: {
    masteryScores: mongoose.Schema.Types.Mixed, // Object with topic:score pairs
    topTopics: [{
      topic: String,
      mastery: Number
    }],
    weakTopics: [{
      topic: String,
      mastery: Number
    }]
  },
  allRecommendations: [{
    topic: String,
    predictedSuccessRate: Number,
    reason: String
  }],
  source: {
    type: String,
    enum: ['dkt-model', 'rule-based', 'fallback'],
    default: 'dkt-model'
  },
  timestamp: {
    type: Date,
    default: Date.now,
    index: true
  }
});

// Indexes
recommendationSchema.index({ userId: 1, timestamp: -1 });
recommendationSchema.index({ recommendationType: 1 });

module.exports = mongoose.model('Recommendation', recommendationSchema);

